collections:
  recommendations:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recommendations"
    values:
      layout: "recommendation"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: ""
url: "https://andrewpetz.github.io"